[project]
name = "modelfreelv"
version = "0.1.0"
description = "Model-Free Voltage Estimation of Low Voltage Electrical Power Distribution Systems using Smart Meter Data"
authors = [
    { name = "Dr Emilio J. Palacios-Garcia", email = "epalacios-garcia@ucc.ie" },
    { name = "Anthony O'Malley", email = "<anthonyomalley999@gmail.com>" },
    { name = "Dr Barry P. Hayes", email = "<barry.hayes@ucc.ie>" },
]
license = "MIT"
requires-python = ">=3.13,<3.14"
dependencies = [
    "numpy (>=2.4.6,<3.0.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "jupyterlab (>=4.5.7,<5.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "scipy (>=1.17.1,<2.0.0)",
    "matplotlib (>=3.10.9,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "dss-python[plot] (>=0.15.7,<0.16.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "xlrd (>=2.0.2,<3.0.0)",
    "jupyterlab-git (>=0.53.0,<0.54.0)",
    "altdss (>=0.2.4,<0.3.0)",
    "opendssdirect-py (>=0.9.4,<0.10.0)",
    "ipympl (>=0.10.0,<0.11.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
